#!/bin/sh
#
# Perform necessary rbbcc setup steps
# after package is installed.
#

PROGNAME=`basename $0`
INSTALLER_DIR=/opt/rbbcc
PREFIX="/usr"

error_exit()
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

rm -f $PREFIX/bin/rbbcc
ln -sf $INSTALLER_DIR/bin/rbbcc $PREFIX/bin || error_exit "Cannot link rbbcc to $PREFIX/bin"
chown -Rh 0:0 $INSTALLER_DIR

echo "Thank you for installing rbbcc! (https://github.com/udzura/rbbcc)"

exit 0
