name: Upload Debs

on:
  push:
    tags:
    - '*'

jobs:
  release:
    name: Upload Debs

    strategy:
      matrix:
        target: [rbbcc, allbcc]
        distro: [focal, bionic, xenial]

    runs-on: ubuntu-18.04
    container: docker.io/udzura/omnibus-rbbcc-builder:${{ matrix.distro }}
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Detect Version
      id: detect_version
      run: |
        echo "::set-output name=current_tag::$(echo ${{ github.ref }} | awk -F'/' '{print $3}')"
    - name: Cache Omnibus Stuff
      id: cache-omnibus
      uses: actions/cache@v2
      with:
        path: /var/cache/omnibus
        key: ${{ runner.os }}-${{ matrix.distro }}-var_cache_omnibus
    - name: Build
      env:
        VERSION: ${{ steps.detect_version.outputs.current_tag }}
      run: ./build.sh ${{ matrix.target }}
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload Release Asset
      id: upload_release_asset 
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: "./pkg/${{ matrix.target }}_${{ steps.detect_version.outputs.current_tag }}~${{ matrix.distro }}-1_amd64.deb"