# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Test Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        target: [rbbcc]
        distro: [bionic, xenial]

    runs-on: ubuntu-18.04
    container: docker.io/udzura/omnibus-rbbcc-builder:${{ matrix.distro }}

    steps:
    - uses: actions/checkout@v2
    - name: Cache Omnibus Stuff
      id: cache-omnibus
      uses: actions/cache@v2
      with:
        path: /var/cache/omnibus
        key: ${{ runner.os }}-${{ matrix.distro }}-var_cache_omnibus
    - name: Run Build
      run: ./build.sh ${{ matrix.target }}
